Style/FrozenStringLiteralComment:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/FormatStringToken:
  EnforcedStyle: template
Metrics/LineLength:
  Max: 120
Layout/AlignHash:
  Enabled: false
Layout/IndentationConsistency:
  EnforcedStyle: rails